
=pod

=head1 NAME

Perl 5 MOP - Internals - Classes

=head1 DESCRIPTION

Now we have arrived at classes, which really should be thought
of as simply being factories for instances. In this proposal
we treat classes as first class citizens in that they too are
just instances of the class C<Class>.

B<AUTHORS NOTE>

It is important to note throughout this document the punctuation
used on the word "class". When you see the lowercase "class" it
is referring to the concept of a class, but when you see the
uppercase "Class" this is referring to the specific class whose
name is "Class".

=head2 The importance of meta-circularity

XXX - meta-circularity provides extensibility
XXX - Perl OO is known for its extensibility
XXX - meta-circularity should provide that same level of
      extensibility and more, in a safe and verifiable way

=head2 The parts of a class

=over 4

=item B<$name>

=item B<$version>

=item B<$authority>

=item B<@superclasses>

=item B<%attributes>

=item B<%methods>

=item B<$constructor>

=item B<$destructor>

=back

=head1 AUTHOR

Stevan Little E<lt>stevan.little@iinteractive.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2011 Infinity Interactive, Inc.

L<http://www.iinteractive.com>

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut