=pod

=head1 NAME

Perl 5 MOP - Meta Object Protocol - Introduction

=head1 DESCRIPTION

This is an introduction to the MOP oriented documents of
this proposal.

=head2 What is a MOP?

A MOP is a Meta Object Protocol, which is essentially just
an API for an object system. Just as an API for network
communications might model things like Sockets and Packets,
a MOP models things like Classes, Method, Attributes and
Instances.

One of my favorite ways to describe a MOP is as follows:

  It is an abstraction of a system of abstractions that is
  used to build abstractions.

That is to say, it is an abstraction (the MOP) of a system
of abstractions (classes and objects) that is used to build
abstractions (the classes you define).






Class is an instance of Class
Object is an instance of Class
Class is a subclass of Object

Here is this represented visually.

  ---> is subclass of
  ...> is instance of

       .....
       :   :
       V   :
       Class -----+
         ^        |
         :        |
      Object <----+

=head1 AUTHOR

Stevan Little E<lt>stevan.little@iinteractive.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2011 Infinity Interactive, Inc.

L<http://www.iinteractive.com>

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut