/* DO NOT EDIT -- generated by Devel::CallParser version 0.001 */
#ifndef C8K61oRQKxigiqmUlVdk_INCLUDED_callparser0
#define C8K61oRQKxigiqmUlVdk_INCLUDED_callparser0 1
#ifndef PERL_VERSION
 #error you must include perl.h before callparser0.h
#elif !(PERL_REVISION == 5 && PERL_VERSION == 14 && PERL_SUBVERSION == 0)
 #error this callparser0.h is for Perl 5.14.0 only
#endif /* Perl version mismatch */
typedef OP *(*Perl_call_parser)(pTHX_ GV *, SV *, U32 *);
#define CALLPARSER_PARENS    0x00000001
#define CALLPARSER_STATEMENT 0x00000002
PERL_CALLCONV void C8K61oRQKxigiqmUlVdk_gcp0(pTHX_ CV *, Perl_call_parser *, SV **);
#define Perl_cv_get_call_parser C8K61oRQKxigiqmUlVdk_gcp0
#define cv_get_call_parser(cv, fp, op) Perl_cv_get_call_parser(aTHX_ cv, fp, op)
PERL_CALLCONV void C8K61oRQKxigiqmUlVdk_scp0(pTHX_ CV *, Perl_call_parser, SV *);
#define Perl_cv_set_call_parser C8K61oRQKxigiqmUlVdk_scp0
#define cv_set_call_parser(cv, f, o) Perl_cv_set_call_parser(aTHX_ cv, f, o)
#endif /* !C8K61oRQKxigiqmUlVdk_INCLUDED_callparser0 */
